### PR TITLE
General improvements

### PR DESCRIPTION
**Pull request by rustkas**
- README.md
  - Add badges.
- rebar3.config
  - Do refactoring
- Makefile
  - Do refactoring
- Add doc folder
  - Add documentation generation presetts
- Fix xref warning related to tests.
- Add examples of using Exif data API.
  1. [exif_reader_app]([exif_reader_app]) Simple OTP Application.
  2. [exif_web_viewer]([exif_web_viewer]) EXIF data web viewer.

### CODE REVIEW

**Comment by rustkas** [comment]
The PR [Fix typo](https://github.com/erlangpack/erlang_exif/pull/1) is this PR too.

**Comment by mworrell** [comment]
@rustkas Sorry, in the meantime rebar3 is updated and will not run on 22 anymore.

Could you change the test matrix:

https://github.com/erlangpack/erlang_exif/blob/master/.github/workflows/test.yml#L21

To `23, 24, 25` ?

**Comment by mworrell** [comment]
I found that I could edit your branch for this small change :-)

**Comment by mworrell** [comment]
Thanks again!

**Comment by rustkas** [comment]
> Thanks again!

Thank you! Studying this project was fun.

**Comment by rustkas** [comment]
It is very important to take a break from a project for a while and get back to it. I have found small shortcomings which I would like to fix.

**Pull request merged**
